### ISSUE TITLE
有没有办法提高分辨率

### ISSUE THREAD

**Issue by uvery9** [yuxie2025/douyin#3]
有没有办法提高分辨率呢？目前只能下载1024P的视频。原视频可能在1920P

**Comment by yuxie2025** [comment]
哪里的视频，方便的提供一个测试链接，方便修改

**Comment by uvery9** [comment]
开业舞蹈 # 全一you女团 # 你来过现场吗 # 感受舞台魅力 # 活动现场 # 舞台视角  https://v.douyin.com/iUCR8Lm4/ 复制此链接，打开Dou音火山版搜索，直接观看视频！

这个视频实际上能下载到1080P，现在下载只有540P.
一般的视频解析网站是可以解析到最高清的，如YouTube下载工具。

![image](https://github.com/user-attachments/assets/aa00351a-29c9-4b24-9fda-dd24c492f3dd)
![image](https://github.com/user-attachments/assets/0cdb070d-9809-46df-b92e-451e0d845793)

**Comment by yuxie2025** [comment]
方案不一样，只能嗅探到当前播放视频的分辨率，可用尝试播放页面清晰度选择
